version: '3.1'
services:
  rails_postgres:
    image: postgres
    container_name: rails_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ruby_app_dev
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - rails-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql

  rails_app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: rails_app
    command: bundle install && rake db:create && bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    networks:
      - rails-network
    volumes:
      - ..:/blogstrap:cached
      - ..:/home/ruby/app

networks:
  rails-network:
    driver: bridge
